"""add verification_expiry column in user models

Revision ID: 0ca61e43df19
Revises: b727f939e3ab
Create Date: 2024-11-23 04:46:14.357477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ca61e43df19'
down_revision: Union[str, None] = 'b727f939e3ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verification_expiry', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verification_expiry')
    # ### end Alembic commands ###
