"""add firebase_uid column

Revision ID: 3018126567eb
Revises: a3b097f36dd4
Create Date: 2024-10-06 10:23:35.655508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3018126567eb'
down_revision: Union[str, None] = 'a3b097f36dd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firebase_uid', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'firebase_uid')
    # ### end Alembic commands ###
