"""add customer_id column in courier models

Revision ID: 35d565869bf1
Revises: 6aea76ac566d
Create Date: 2024-11-12 06:16:56.124941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '35d565869bf1'
down_revision: Union[str, None] = '6aea76ac566d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('couriers', sa.Column('customer_id', mysql.CHAR(length=36), nullable=False))
    op.alter_column('couriers', 'service_type',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.create_index(op.f('ix_couriers_customer_id'), 'couriers', ['customer_id'], unique=False)
    op.create_foreign_key(None, 'couriers', 'users', ['customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'couriers', type_='foreignkey')
    op.drop_index(op.f('ix_couriers_customer_id'), table_name='couriers')
    op.alter_column('couriers', 'service_type',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.drop_column('couriers', 'customer_id')
    # ### end Alembic commands ###
