"""Add is_active column in cart models

Revision ID: 486bab4dbae7
Revises: b8aba3d0e39b
Create Date: 2024-11-07 19:30:51.192690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '486bab4dbae7'
down_revision: Union[str, None] = 'b8aba3d0e39b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_products', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart_products', 'is_active')
    # ### end Alembic commands ###
