"""Add 'capture' status to transactionstatusenum

Revision ID: 56ff2a7bd06f
Revises: de953c4bbe35
Create Date: 2024-12-05 10:28:21.506385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56ff2a7bd06f'
down_revision: Union[str, None] = 'de953c4bbe35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Tambahkan 'capture' ke enum yang sudah ada
    op.execute("ALTER TYPE transactionstatusenum ADD VALUE 'capture';")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
