"""Add variant_id column in CART Models

Revision ID: 60463190e15f
Revises: dbde23007f1c
Create Date: 2024-11-04 10:21:45.794555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60463190e15f'
down_revision: Union[str, None] = 'dbde23007f1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_products', sa.Column('variant_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_cart_products_variant_id'), 'cart_products', ['variant_id'], unique=False)
    op.create_foreign_key(None, 'cart_products', 'pack_types', ['variant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cart_products', type_='foreignkey')
    op.drop_index(op.f('ix_cart_products_variant_id'), table_name='cart_products')
    op.drop_column('cart_products', 'variant_id')
    # ### end Alembic commands ###
