"""add many item  column to courier  model

Revision ID: 6aea76ac566d
Revises: 4c78b982fa17
Create Date: 2024-11-11 12:06:31.689043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6aea76ac566d'
down_revision: Union[str, None] = '4c78b982fa17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('couriers', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('couriers', sa.Column('service_type', sa.String(length=30), nullable=False))
    op.add_column('couriers', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('couriers', sa.Column('cost', sa.Float(), nullable=True))
    op.add_column('couriers', sa.Column('estimated_delivery', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('couriers', 'estimated_delivery')
    op.drop_column('couriers', 'cost')
    op.drop_column('couriers', 'is_active')
    op.drop_column('couriers', 'service_type')
    op.drop_column('couriers', 'phone_number')
    # ### end Alembic commands ###
