"""updated column foreign key between pack and product models

Revision ID: 6cf37fd41d64
Revises: 91a82e4e818c
Create Date: 2024-10-21 16:11:52.459075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6cf37fd41d64'
down_revision: Union[str, None] = '91a82e4e818c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pack_types', sa.Column('product_id', mysql.CHAR(length=36), nullable=True))
    op.create_foreign_key(None, 'pack_types', 'products', ['product_id'], ['id'])
    op.drop_constraint('products_pack_type_id_fkey', 'products', type_='foreignkey')
    op.drop_column('products', 'pack_type_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('pack_type_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('products_pack_type_id_fkey', 'products', 'pack_types', ['pack_type_id'], ['id'])
    op.drop_constraint(None, 'pack_types', type_='foreignkey')
    op.drop_column('pack_types', 'product_id')
    # ### end Alembic commands ###
