"""Add photo_url column to ProductionModel

Revision ID: a443cd47ede1
Revises: 2eb61b11a7a0
Create Date: 2024-10-19 21:26:44.313892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a443cd47ede1'
down_revision: Union[str, None] = '2eb61b11a7a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'display_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=True,
               postgresql_using="display_id::integer")  # Add USING clause here
    op.drop_index('ix_articles_display_id', table_name='articles')
    op.create_index(op.f('ix_articles_display_id'), 'articles', ['display_id'], unique=False)
    op.add_column('productions', sa.Column('photo_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productions', 'photo_url')
    op.drop_index(op.f('ix_articles_display_id'), table_name='articles')
    op.create_index('ix_articles_display_id', 'articles', ['display_id'], unique=True)
    op.alter_column('articles', 'display_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###