"""change type data column customer_id of shipment adresses model

Revision ID: ad1c26b7bd74
Revises: 8bb6213d305a
Create Date: 2024-10-16 08:31:30.373421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ad1c26b7bd74'
down_revision: Union[str, None] = '8bb6213d305a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shipment_addresses', 'customer_id',
               existing_type=sa.VARCHAR(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shipment_addresses', 'customer_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.VARCHAR(length=36),
               existing_nullable=True)
    # ### end Alembic commands ###
