"""change type data of estimated_Delivery from integer to string(15)

Revision ID: b727f939e3ab
Revises: bd49c3abca51
Create Date: 2024-11-18 12:43:13.086595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b727f939e3ab'
down_revision: Union[str, None] = 'bd49c3abca51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('couriers', 'estimated_delivery',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=15),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('couriers', 'estimated_delivery',
               existing_type=sa.String(length=15),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
