"""add new column in courier and shipment models

Revision ID: bd49c3abca51
Revises: 35d565869bf1
Create Date: 2024-11-18 08:07:21.285476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bd49c3abca51'
down_revision: Union[str, None] = '35d565869bf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipment_addresses', sa.Column('city_id', sa.Integer(), nullable=True))
    op.add_column('shipments', sa.Column('customer_id', mysql.CHAR(length=36), nullable=True))
    op.create_foreign_key(None, 'shipments', 'users', ['customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shipments', type_='foreignkey')
    op.drop_column('shipments', 'customer_id')
    op.drop_column('shipment_addresses', 'city_id')
    # ### end Alembic commands ###
