"""Add index=True in all needed column models

Revision ID: dbde23007f1c
Revises: 6cf37fd41d64
Create Date: 2024-10-25 07:29:46.752449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbde23007f1c'
down_revision: Union[str, None] = '6cf37fd41d64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_couriers_courier_name'), 'couriers', ['courier_name'], unique=False)
    op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_orders_shipment_id'), 'orders', ['shipment_id'], unique=False)
    op.create_index(op.f('ix_pack_types_discount'), 'pack_types', ['discount'], unique=False)
    op.create_index(op.f('ix_pack_types_product_id'), 'pack_types', ['product_id'], unique=False)
    op.drop_constraint('payments_order_id_key', 'payments', type_='unique')
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=True)
    op.create_index(op.f('ix_products_price'), 'products', ['price'], unique=False)
    op.create_index(op.f('ix_ratings_product_id'), 'ratings', ['product_id'], unique=False)
    op.create_index(op.f('ix_shipments_courier_id'), 'shipments', ['courier_id'], unique=False)
    op.create_index(op.f('ix_wishlists_product_id'), 'wishlists', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wishlists_product_id'), table_name='wishlists')
    op.drop_index(op.f('ix_shipments_courier_id'), table_name='shipments')
    op.drop_index(op.f('ix_ratings_product_id'), table_name='ratings')
    op.drop_index(op.f('ix_products_price'), table_name='products')
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.create_unique_constraint('payments_order_id_key', 'payments', ['order_id'])
    op.drop_index(op.f('ix_pack_types_product_id'), table_name='pack_types')
    op.drop_index(op.f('ix_pack_types_discount'), table_name='pack_types')
    op.drop_index(op.f('ix_orders_shipment_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
    op.drop_index(op.f('ix_couriers_courier_name'), table_name='couriers')
    # ### end Alembic commands ###
